# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CSC699Hwk1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CSC699Hwk1
  pod 'Alamofire', '~> 4.4'
  pod 'AlamofireImage'

  target 'CSC699Hwk1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CSC699Hwk1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
